// "File over app" export: the reader takes the story as a self-contained .html
// that opens offline in any browser, with no platform.
//
// The HTML embeds the `Story` (JSON), the player runtime (an IIFE bundle
// pre-generated by esbuild) and the stage CSS. ZERO network requests: no
// external fonts/CDN (falls back to system-ui).

import type { Story } from "./engine";
import { standaloneBundle } from "./generated/standaloneBundle";

export interface ExportLabels {
  end: string;
  playAgain: string;
  structure: string;
}

const DEFAULT_LABELS: ExportLabels = {
  end: "The End 🌱",
  playAgain: "↺ Play again",
  structure: "Structure:",
};

/** Escapes ``</script>`` so inline JSON/JS does not close the tag. */
function safe(json: string): string {
  return json.replace(/<\/(script)/gi, "<\\/$1");
}

/** Builds the self-contained HTML for a story (a string ready to save). */
export function exportHtml(
  story: Story,
  options: { labels?: Partial<ExportLabels> } = {},
): string {
  const labels: ExportLabels = { ...DEFAULT_LABELS, ...options.labels };
  const title = (story.title || "My story").replace(/[<>]/g, "");
  const author = (story.author || "").replace(/[<>]/g, "");
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${title}</title>
<style>
  :root { font-family: system-ui, -apple-system, sans-serif; }
  body { margin: 0; background: #f4f4f5; color: #27272a; display: flex; min-height: 100vh;
    align-items: center; justify-content: center; padding: 16px; box-sizing: border-box; }
  .wrap { width: 100%; max-width: 760px; }
  h1 { font-size: 18px; margin: 0 0 4px; }
  .meta { color: #71717a; font-size: 13px; margin: 0 0 12px; }
  .stage-wrap { background: #fff; border-radius: 16px; padding: 16px;
    box-shadow: 0 6px 24px rgba(0,0,0,0.08); }
  .stage { width: 100%; height: auto; border-radius: 12px; display: block; background: #dbeafe; }
  .choices { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 14px; align-items: center; }
  .choice-btn { background: #fff; color: #5b21b6; border: 2px solid #7c3aed;
    border-radius: 12px; padding: 10px 16px; font: inherit; font-weight: 600; cursor: pointer; }
  .choice-btn:hover { background: #f5f3ff; }
  .choice-btn.secondary { border-color: #a1a1aa; color: #52525b; }
  .ending { font-size: 18px; font-weight: 700; color: #5b21b6; }
  .structure { margin-top: 14px; font: 600 12px ui-monospace, monospace; color: #10b981;
    background: #ecfdf5; border-radius: 10px; padding: 8px 12px; }
  footer { margin-top: 12px; text-align: center; color: #a1a1aa; font-size: 11px; }
</style>
</head>
<body>
<div class="wrap">
  <h1>${title}</h1>
  ${author ? `<p class="meta">by ${author}</p>` : ""}
  <div class="stage-wrap"><div id="stage"></div></div>
  <footer>Interactive story.</footer>
</div>
<script>window.__STORY__=${safe(JSON.stringify(story))};window.__LABELS__=${safe(
    JSON.stringify(labels),
  )};</script>
<script>${standaloneBundle}</script>
</body>
</html>`;
}

/** Triggers the download of the HTML as a file (in the browser). */
export function downloadHtml(filename: string, html: string): void {
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
